/* ----------------------PROJECT-------------------------*/
export const FETCH_PROJECTS_START = "FETCH_PROJECTS_START";
export const FETCH_PROJECTS_SUCCESS = "FETCH_PROJECTS_SUCCESS";
export const FETCH_PROJECTS_FAIL = "FETCH_PROJECTS_FAIL";

export const CREATE_PROJECT_START = "CREATE_PROJECT_START";
export const CREATE_PROJECT_SUCCESS = "CREATE_PROJECT_SUCCESS";
export const CREATE_PROJECT_FAIL = "CREATE_PROJECT_FAIL";

export const DELETE_PROJECT_START = "DELETE_PROJECT_START";
export const DELETE_PROJECT_SUCCESS = "DELETE_PROJECT_SUCCESS";
export const DELETE_PROJECT_FAIL = "DELETE_PROJECT_FAIL";

export const EDIT_PROJECT_START = "EDIT_PROJECT_START";
export const EDIT_PROJECT_SUCCESS = "EDIT_PROJECT_SUCCESS";
export const EDIT_PROJECT_FAIL = "EDIT_PROJECT_FAIL";

/*-----------------------TIME------------------------------*/

export const FETCH_TIME_START = "FETCH_TIME_START";
export const FETCH_TIME_SUCCESS = "FETCH_TIME_SUCCESS";
export const FETCH_TIME_FAIL = "FETCH_TIME_FAIL";

export const CREATE_TIME_START = "CREATE_TIME_START";
export const CREATE_TIME_SUCCESS = "CREATE_TIME_SUCCESS";
export const CREATE_TIME_FAIL = "CREATE_TIME_FAIL";

export const DELETE_TIME_START = "DELETE_TIME_START";
export const DELETE_TIME_SUCCESS = "DELETE_TIME_SUCCESS";
export const DELETE_TIME_FAIL = "DELETE_TIME_FAIL";